pool:
  vmImage: ubuntu-latest

steps:
- task: Docker@2
  inputs:
    containerRegistry: 'whcca927_docker'
    repository: 'newregsitry9908'
    command: 'buildAndPush'
    Dockerfile: 'app/Dockerfile'

